spring:
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
    username: rm550415
    password: 080704
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: false

server:
  port: 80
